apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: databricks-proxy-executable
  annotations:
    scenarios.ai.sap.com/description: "Proxy Node.js: AI Core -> Databricks"
    scenarios.ai.sap.com/name: "ai-container-slc"
    executables.ai.sap.com/description: "Proxy Node.js: AI Core -> Databricks"
    executables.ai.sap.com/name: "Databricks Proxy"
  labels:
    scenarios.ai.sap.com/id: "scenario-ai"
    ai.sap.com/version: "2.0"
spec:
  inputs:
    parameters:
      - name: databricksUrl
      - name: databricksToken
  template:
    apiVersion: serving.kserve.io/v1beta1
    kind: Predictor
    metadata:
    spec:
      containers:
        - name: kserve-container
          image: "docker.io/dioferoviedo/databricks-proxy:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DATABRICKS_URL
              value: "{{inputs.parameters.databricksUrl}}"
            - name: DATABRICKS_TOKEN
              value: "{{inputs.parameters.databricksToken}}"
